### ISSUE TITLE
Lets discuss instance detection

### ISSUE THREAD

**Issue by Apollon77** [Jey-Cee/ioBroker.device-manager#21]
The better idea then "spamming" all instances with a message is that instances define in it's io-package that they support devicemanagement.
With js-controller 5 we introduced common.supportedMessages ... used like https://github.com/iobroker-community-adapters/ioBroker.email/blob/master/io-package.json#L129-L132

I propose to discuss (@foxriver76 FYI) to enhance that by a new property "deviceManagement": "v1" to also include the version (or we do true&false and get version as now from a first message).

This enables the deviceManagement adater to directly know whats up and what is supported. Additionally the adapter shpuld check if the device is alive before sending the message ... then also the timeout handling can be relaxed a bit...

**Comment by DutchmanNL** [comment]
2 questions 

@Apollon77 
Message will only be answered/send to instance which have massaging listener implements right ?
Which would mean there is no impact on all adapters , to make it a little smaller, but indeed maybe unneeded/wanted events 

maybe it can be useful to trigger it and receive some kind of info for future purposes, so we should make a decision keeping that in mind

@Jey-Cee 
What is the added value sending messages to adapter not having an integration with this one  ?

**Comment by Apollon77** [comment]
Controller sends to the instances you specify. Worst case it never gets and answer and then fails it after 30s or such. 
we introduced this new option especially to prevent „guessing“ if n adapter supports a certain topic. Also because using a 10ms timeout can lead to wrong results on systems under load or such.

**Comment by Jey-Cee** [comment]
Makes sense, i will change that.
I choose deviceManager: boolean while the api information comes with the instance information message.

> Also because using a 10ms timeout can lead to wrong results on systems under load or such.

Yes, this is happening on net-tools.

@DutchmanNL can you please add this prop to wled.

@foxriver76 please add the new prop "deviceManager: boolean" for common.supportedMessages to ioBroker types. THX.

**Comment by DutchmanNL** [comment]
> @DutchmanNL can you please add this prop to wled.

done

**Comment by DutchmanNL** [comment]
I think this issue can be closed @Apollon77 @Jey-Cee :)
